module.exports = {
  docsSidebar: [
    "index",
    "navigator",
    {
      type: "category",
      label: "Core Documents",
      collapsible: true,
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "core-docs" }],
    },
    {
      type: "category",
      label: "Architecture Documents",
      collapsible: true,
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "architecture-docs" }],
    },
    {
      type: "category",
      label: "Operator Material",
      collapsible: true,
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "operators" }],
    },
    {
      type: "category",
      label: "Integrations and Tooling",
      collapsible: true,
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "integration-docs" }],
    },
    {
      type: "category",
      label: "Release and Recovery",
      collapsible: true,
      collapsed: true,
      items: ["release-runbook", "release-troubleshooting"],
    },
  ],
};
