module.exports = {
  docsSidebar: [
    "index",
    "navigator",
    {
      type: "category",
      label: "Основные документы",
      collapsible: true,
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "core-docs" }],
    },
    {
      type: "category",
      label: "Архитектурные документы",
      collapsible: true,
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "architecture-docs" }],
    },
    {
      type: "category",
      label: "Операторские материалы",
      collapsible: true,
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "operators" }],
    },
    {
      type: "category",
      label: "Интеграции и tooling",
      collapsible: true,
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "integration-docs" }],
    },
    {
      type: "category",
      label: "Release и восстановление",
      collapsible: true,
      collapsed: true,
      items: ["release-runbook", "release-troubleshooting"],
    },
  ],
};
