use super::*;

pub(super) fn windows_preset(platform: AutoPlatform, variant: usize, seed: u64) -> IdentityPreset {
    match variant {
    0 => desktop_preset(
    platform,
    IdentityCore {
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36".to_string(),
    platform: "Win32".to_string(),
    platform_version: "10.0".to_string(),
    brand: "Chromium".to_string(),
    brand_version: "124".to_string(),
    vendor: "Google Inc.".to_string(),
    vendor_sub: "".to_string(),
    product_sub: "20030107".to_string(),
    },
    HardwareProfile {
    cpu_threads: 8,
    max_touch_points: 0,
    device_memory_gb: 16,
    },
    ScreenProfile {
    width: 1920,
    height: 1080,
    device_pixel_ratio: 1.0,
    avail_width: 1920,
    avail_height: 1040,
    color_depth: 24,
    },
    WindowProfile {
    outer_width: 1920,
    outer_height: 1040,
    inner_width: 1898,
    inner_height: 948,
    screen_x: 0,
    screen_y: 0,
    },
    LocaleProfile {
    navigator_language: "en-US".to_string(),
    languages: vec!["en-US".to_string(), "en".to_string()],
    do_not_track: "1".to_string(),
    timezone_iana: "America/New_York".to_string(),
    timezone_offset_minutes: 300,
    },
    GeoProfile {
    latitude: 40.7128,
    longitude: -74.006,
    accuracy_meters: 24.0,
    },
    WebGlProfile {
    vendor: "Google Inc. (Intel)".to_string(),
    renderer: "ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0)".to_string(),
    params_json: "{\"maxTextureSize\":16384}".to_string(),
    },
    &["Arial", "Segoe UI", "Calibri", "Verdana"],
    BatteryProfile {
    charging: true,
    level: 0.92,
    },
    seed,
    ),
    1 => desktop_preset(
    platform,
    IdentityCore {
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0".to_string(),
    platform: "Win32".to_string(),
    platform_version: "10.0".to_string(),
    brand: "Firefox".to_string(),
    brand_version: "126".to_string(),
    vendor: "".to_string(),
    vendor_sub: "".to_string(),
    product_sub: "20100101".to_string(),
    },
    HardwareProfile {
    cpu_threads: 12,
    max_touch_points: 0,
    device_memory_gb: 16,
    },
    ScreenProfile {
    width: 2560,
    height: 1440,
    device_pixel_ratio: 1.0,
    avail_width: 2560,
    avail_height: 1400,
    color_depth: 24,
    },
    WindowProfile {
    outer_width: 2560,
    outer_height: 1400,
    inner_width: 2516,
    inner_height: 1308,
    screen_x: 0,
    screen_y: 0,
    },
    LocaleProfile {
    navigator_language: "en-GB".to_string(),
    languages: vec!["en-GB".to_string(), "en".to_string()],
    do_not_track: "1".to_string(),
    timezone_iana: "Europe/London".to_string(),
    timezone_offset_minutes: 0,
    },
    GeoProfile {
    latitude: 51.5072,
    longitude: -0.1276,
    accuracy_meters: 18.0,
    },
    WebGlProfile {
    vendor: "Mozilla".to_string(),
    renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Direct3D11 vs_5_0 ps_5_0)".to_string(),
    params_json: "{\"antialias\":true}".to_string(),
    },
    &["Arial", "Segoe UI", "Tahoma", "Trebuchet MS"],
    BatteryProfile {
    charging: false,
    level: 0.67,
    },
    seed,
    ),
    _ => desktop_preset(
    platform,
    IdentityCore {
    user_agent: "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36".to_string(),
    platform: "Win32".to_string(),
    platform_version: "10.0".to_string(),
    brand: "Chromium".to_string(),
    brand_version: "122".to_string(),
    vendor: "Google Inc.".to_string(),
    vendor_sub: "".to_string(),
    product_sub: "20030107".to_string(),
    },
    HardwareProfile {
    cpu_threads: 4,
    max_touch_points: 0,
    device_memory_gb: 8,
    },
    ScreenProfile {
    width: 1366,
    height: 768,
    device_pixel_ratio: 1.0,
    avail_width: 1366,
    avail_height: 728,
    color_depth: 24,
    },
    WindowProfile {
    outer_width: 1366,
    outer_height: 728,
    inner_width: 1340,
    inner_height: 636,
    screen_x: 0,
    screen_y: 0,
    },
    LocaleProfile {
    navigator_language: "de-DE".to_string(),
    languages: vec!["de-DE".to_string(), "de".to_string(), "en-US".to_string()],
    do_not_track: "1".to_string(),
    timezone_iana: "Europe/Berlin".to_string(),
    timezone_offset_minutes: -60,
    },
    GeoProfile {
    latitude: 52.52,
    longitude: 13.405,
    accuracy_meters: 26.0,
    },
    WebGlProfile {
    vendor: "Google Inc. (Intel)".to_string(),
    renderer: "ANGLE (Intel, Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)".to_string(),
    params_json: "{\"maxTextureSize\":16384}".to_string(),
    },
    &["Arial", "Segoe UI", "Calibri"],
    BatteryProfile {
    charging: true,
    level: 0.79,
    },
    seed,
    ),
    }
}
